### ISSUE TITLE
Appreciate previously incorrectly deprecated tokens 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#102]
## Describe the bug

In a previous work item, the desired output was to deprecate the `on-dark` tokens. For the most part this was correctly done. But in some minor cases, there are incorrectly deprecated tokens that need to be re-appreciated. 

Those tokens are:

1. primary text on dark
2. tbd.... 

(@leeejune is putting together a document that will map out the ones that to be reverted and the ones to be renamed.)

E.g. auro-button uses `--auro-color-text-primary-on-dark`

## dependency 

- https://github.com/AlaskaAirlines/AuroDesignTokens/issues/98

## Exit criteria 

Correctly identify all the `on-dark` tokens that need to be retained and re-appreciate them back that mainstream output.

**Comment by leeejune** [comment]
See document here: https://alaskaair-my.sharepoint.com/:x:/p/june_lee/EdaRLHWZS1ZFs4s8kFLJ15MBTYqJ52scti3SHvmK6-XrJg?e=12uuMg
