### ISSUE TITLE
Support grid width token

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#112]
## Is your feature request related to a problem? Please describe.

When building out new grid features for WCSS, there is a need for a new `grid-spacing` token. 

## Describe the solution you'd like

Add 

```
grid-spacing: 8px
```

## Exit criteria 

This issue is complete once the new token has been added and released.

**Comment by leeejune** [comment]
<img width="598" alt="Screenshot 2023-05-16 at 10 59 31 AM" src="https://github.com/AlaskaAirlines/AuroDesignTokens/assets/55998746/93879921-b80c-4319-a406-15beaf840165">
https://www.figma.com/file/VpUz89Ov6ImBpY5YvzYbZW/Auro-toolkit?type=design&node-id=0-1102&t=4tmL41j38W3d0kPT-11

Are you referring to the gutter spacing? If so, it would be different across the breakpoints so we'd need sizes in the token name too.

**Comment by blackfalcon** [comment]
The coded tokens for this value have been found https://github.com/AlaskaAirlines/AuroDesignTokens/blob/master/src/grid-gutter.json

The real issue is that these and other tokes are NOT showing up in the AuroDocsite.

**Comment by blackfalcon** [comment]
Work moved to AuroDocSite issue 

- https://github.com/AlaskaAirlines/AuroDocsSite/issues/126
