### ISSUE TITLE
As an Auro Developer, I need a list of all our Design Token Variable names

### ISSUE THREAD

**Issue by Patrick-Daly-AA** [AlaskaAirlines/AuroDesignTokens#114]
# General Support Request

1. Run the build
2. Get the list of the token names from the built CSS files and put them into a list (preferably a spreadsheet)
3. Optionally, you can do an npm package install of the tokens, and that will also contain the built CSS files with compiled token names

## Context

As we embark on working on theming, we will need a list of all our current design token variable names so that we can find and replace them in the future.

**Comment by Patrick-Daly-AA** [comment]
Turns out we already have this on the doc site: https://auro.alaskaair.com/getting-started/developers/design-tokens#gsc.tab=0

**Comment by blackfalcon** [comment]
A list of all the supported and deprecated names are in the doc site

https://auro.alaskaair.com/getting-started/developers/design-tokens
https://auro.alaskaair.com/getting-started/developers/design-tokens/deprecated
