### ISSUE TITLE
Copy all Token content and functionality to Jetstream repo

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#119]
## Is your feature request related to a problem? Please describe.

We need to make a copy of the Auro Design Token repo for the Jetstream repo

## Describe the solution you'd like

Once the tasks for updating to Node 18 and the renaming of the prefix is complete, all the contents of the Auro Design Token repo can be copied into the Jetstream Design Token repo. 

https://github.com/Alaska-ITS/JetstreamDesignTokens

DO NOT INCLUDE
1. Git history 
2. Changelog history 

Once copied, delete all the tokens not represented in this [spreadsheet](https://alaskaair-my.sharepoint.com/:x:/r/personal/june_lee_alaskaair_com/_layouts/15/Doc.aspx?sourcedoc=%7B752C91D6-4B99-4556-B38B-3C9052C9D793%7D&file=Jetstream%20%26%20Auro%20Alignment.xlsx&action=default&mobileredirect=true).

For the remaining tokens, update their values according to the token map in the previously linked document. 

The install directions need to be updated to illustrate the dependency on Auro Design Tokens to be loaded into the app first and then the Jetstream tokens added after. This will allow the JS token with the same name as an Auro token to override its value. 

## Additional context

Jetstream specific tokens can be added to the JS token repo. This will only be used by Jetstream specific components and there is no need to have an Auro reference. 

## Exit criteria 

This issue will be closed once the content of the Auro design tokens repo has been copied over, without Git history or unnecessary, remaining values are changed, and all content about the tokens are updated to represent this Jetstream theme.

**Comment by jordanjones243** [comment]
This work can be verified via this PR: 
* https://github.com/Alaska-ITS/JetstreamDesignTokens/pull/1
