### ISSUE TITLE
Remove the `onDark` naming convention from dark mode tokens

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/AuroDesignTokens#129]
### General Support Request

Remove the `onDark` naming convention from dark mode tokens

### Possible Solution

Remove the `onDark` naming convention from dark mode tokens and replace them with `default` to match the light mode tokens.

### Additional context

This work needs to be done as the light mode tokens have moved away from the `onLight` and `onDark` naming conventions and now use `default` and `inverse`.

**Comment by blackfalcon** [comment]
This issue has been verified in the linked PR.
