### ISSUE TITLE
Add missing design tokens

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/AuroDesignTokens#137]
### Is your feature request related to a problem? Please describe.

There are a few design tokens that were deprecated but are still in use/are missing:

#### Alias 

~`ds-color-ui-default-inverse: ds-color-brand-breeze-300`~
~`ds-color-ui-hover-inverse: ds-color-brand-breeze-200`~

#### UI active tokens

- [x] `ds-color-ui-active-inverse: ds-color-brand-breeze-200`

#### UI background

- [x] `ds-color-ui-bkg-default-default: #00000008` 
- [x] `ds-color-ui-bkg-default-inverse: #FFFFFF08`
- [x] `ds-color-ui-bkg-hover-inverse: #FFFFFF0F` 

#### border

- [x] `ds-color-border-active-inverse: ds-color-brand-breeze-300`

### Describe the solution you'd like

Add the listed design tokens to the library.

### Additional context

This will resolve: https://github.com/AlaskaAirlines/auro-button/pull/228#discussion_r1416494893

### Exit Criteria
Validate that the new tokens show up on the doc site.

**Comment by jordanjones243** [comment]
`ds-color-ui-default-inverse` and `ds-color-ui-hover-inverse` already exist in our design tokens

**Comment by leeejune** [comment]
> `ds-color-ui-default-inverse` and `ds-color-ui-hover-inverse` already exist in our design tokens
I was referring to the "color palette" page on the doc site and it seems like it's not fully up to date with the "design tokens" page. If it already exists, no need to add it! I'll edit the issue.

<img width="1134" alt="Screenshot 2023-12-12 at 12 17 45 PM" src="https://github.com/AlaskaAirlines/AuroDesignTokens/assets/55998746/28400a76-c105-4fe0-93a3-421687ed29e2">
