### ISSUE TITLE
Auro design tokens: Excursion Theme

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/AuroDesignTokens#151]
### Is your feature request related to a problem? Please describe.

I want the new Excursion Theme tokens available

### Describe the solution you'd like

A set of design tokens available for Excursion Theme

### Exit criteria
The latest excursion Design tokens are included.  Anything that isn't final can be added in a future issue.
Design tokens for the excursion theme can be added to web pages
Design tokens are outputted in a format that works for the app team.

**Comment by Patrick-Daly-AA** [comment]
@leeejune , could you add a link to the design token values for this theme?
