### ISSUE TITLE
Auro design tokens: Jetstream Theme

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/AuroDesignTokens#152]
### Is your feature request related to a problem? Please describe.

I want the new Jetstream Theme tokens available

### Describe the solution you'd like

A set of design tokens available for Jetstream Theme

### Additional context

Basically we'll be porting over the tokens from this repo https://github.com/Alaska-ITS/JetstreamDesignTokens
And we'll follow the pattern established for `excursion` in this PR but with `Jetstream` https://github.com/AlaskaAirlines/AuroDesignTokens/pull/156

### Exit criteria
The latest Jetstream Design tokens are included. Anything that isn't final can be added in a future issue.
Design tokens for the Jetstream theme can be added to web pages
Design tokens are outputted in a format that works for app teams (both the flat and nested format that we did for excursion).
![image](https://github.com/AlaskaAirlines/AuroDesignTokens/assets/5118118/19cb8ff3-7e89-485a-98f5-6206049e2ccc)

**Comment by Patrick-Daly-AA** [comment]
@leeejune , could you please add a link to the Jetstream theme token values?

Additionally, we should put a link in this issue to the Jetstream token repo that already exists.

**Comment by blackfalcon** [comment]
This work is BLOCKED until we have resolved the initial Excursion theme updates. 

https://github.com/AlaskaAirlines/AuroDesignTokens/pull/156
