### ISSUE TITLE
Deprecated tokens with no new ref for colors that are still in use

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#174]
### General Support Request

Please see the following code: 

https://github.com/AlaskaAirlines/AuroDesignTokens/blob/3640b448dba4f12f193521e6bd824218808992ca/src/color/ui.json#L2-L14

All the UI colors have been marked as `deprecated` with no new references. Elements like auro-hyperlink are still using these tokens, e.g. 

```css
--ds-auro-hyperlink-default-color-default: var(--ds-color-text-ui-default-default, #{$ds-color-text-ui-default-default});
```

### Possible Solution

Clearly define what the superceding token should be used for these legacy UI elements. 

### Additional context

This same issue persists for alert colors as well: 

https://github.com/AlaskaAirlines/AuroDesignTokens/blob/3640b448dba4f12f193521e6bd824218808992ca/src/color/alert.json#L1-L15

It appears that the new token to be used is `-ds-color-icon-info-default`? 

### Exit criteria

This issue can be closed once all the new references for these deprecated tokens are identified.

**Comment by braven112** [comment]
closing and will complete with #160
