### ISSUE TITLE
Appears to be an incorrect color spec

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#189]
### Please verify the version of Auro design tokens you have installed

@latest

### Please describe the bug

Please see the screenshot

<img width="1035" alt="Screenshot 2024-11-05 at 4 27 22 PM" src="https://github.com/user-attachments/assets/ea215e1d-00c9-43ce-bd17-c4b67afc2488">

The color `#d4ece4` is a light, soft greenish-blue. This hex color is often described as a mint green or pastel aqua. 

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

A gray token should appear gray? 

### What browsers are you seeing the problem on?

Chrome

### Additional context

n/a

### Exit criteria

This issue can be resolved once there is a decision made to address the `var(--ds-color-base-gray-200)` color.

**Comment by NickingAS** [comment]
The correct hex is #d4d4d4
