### ISSUE TITLE
Alert colors require more research

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#26]
# General Support Request

It was discovered in a recent update to the current site that the alert colors as directed by Auro at this time need to be further researched. 

* `var(--auro-color-alert-advisory-on-light)` was considered to be too alarming. 
* `var(--auro-color-brand-tropical-100)` was recommended and accepted as not being too alarming, but stands out from the rest of the page content.
* `var(--auro-color-brand-midnight-500)` was recommended, but using this as an alert color with the classic UI, was not noticeable. 

## Support request

More color options are requested otherwise situations like this will keep happening. 

The team worked to maintain some level of brand consistency by working within the Auro color palette, but the advisory space gets leadership attention.

In the absence of hardened pre-approved options related to message and tone, uses will continue to be second-guessed causing additional inconsistency and communication issues. 

## Possible Solution

The current alert/messaging color options should be reviewed, tested and clear boundaries of use need to be defined and hardened across the org. 

![](https://user-images.githubusercontent.com/181089/76108679-dfec7880-5f8f-11ea-9c00-b038a7db0f89.png)
![](https://user-images.githubusercontent.com/181089/76108733-fabeed00-5f8f-11ea-83a4-f7b992324f55.png)

## Audit 

https://github.com/AlaskaAirlines/auro/issues/17

**Comment by blackfalcon** [comment]
Unassigned, looking for help

**Comment by sryckman** [comment]
"var(--auro-color-brand-tropical-100) was recommended and accepted as not being too alarming, but stands out from the rest of the page content."

Isn't it supposed to stand out if it's an alert that we want to make sure users see?

**Comment by blackfalcon** [comment]
This issue is extremely old and I am wondering if there is any resolution needed? Due to its age and the fact that there have been very few discussions or interest tells me that this issue has been abandoned and should be closed. 

@vidalmenAS @sryckman what say you? 

If you feel that there are no actions to be taken from this issue, please feel free to close.

**Comment by blackfalcon** [comment]
Due to a lack of interest and feedback, I am electing to close this issue. If and when this is to be revisited, we can bring this back as needed.
