### ISSUE TITLE
JSVariable variable names invalid, possible docs update?

### ISSUE THREAD

**Issue by littleninja** [AlaskaAirlines/AuroDesignTokens#31]
Sorry, there might be a few issues rolled into this. I tried playing with jss and went for our Javascript tokens but wasn't sure how to consume them, so I started with our [Auro docs](https://auro.alaskaair.com/getting-started/developers/design-tokens/install#install-esmodules). There are several JS* files. I noticed `JSData--color.js` has an object structure and I can pull the color like so:

```javascript
import { color } from '@alaskaairux/orion-design-tokens/dist/tokens/JSData--color';
console.log(color.background.lightest.value); // #ffffff 👍🏻
```

## Issue 1
I think token documentation for ESModules might be out of date. It references title case variables like `ColorAlertNotificationOnLight` from `JSVariables--color.js` but current variable names are kebab (see below). Can I use `JSData--color.js` too?

## Issue 2
Next, because the docs suggested `JSVariables--color.js` I looked for the titlecase variables. From the [StyleDictionary configuration](https://github.com/AlaskaAirlines/AuroDesignTokens/blob/a6813252b8e6d4021244337c5ecf03ea8be2abad/scripts/config.json#L250), and from a quick search it looks like this doesn't conform with [rules for accepted identifiers (variable names)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types). The question here is a bit more complicated: the object syntax above is fine, what was the hopeful goal of autogenerated variable names vs. object? Assuming we need the variable name case, I think this would be fixed by using camel or title case (just not kebab).

![image](https://user-images.githubusercontent.com/4391579/97506932-5aac3e80-1939-11eb-9db6-07c6794f43d4.png)

**Comment by blackfalcon** [comment]
Good catch. This file is not really used and what I think happened is with the last major refactor the output file was altered and not caught. 

I am working on a major release for the Tokens that removes all legacy Orion and Classic support, this update will be added to that branch. 

I will also retroactive update the previous version of Tokens to address this bug.
