### ISSUE TITLE
Design tokens: add brand-neutral specs

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/AuroDesignTokens#36]
## Describe the bug
Auro.alaskaair.com Personality Color Palette page is missing all of the neutral colors that exist in our UI kit and the design tokens actually exist, they just aren't displayed in the demo.

## To Reproduce
1. Go to https://auro.alaskaair.com/color/personality-palette-usage
2. The range of Neutral colors are missing:

- var(--auro-color-brand-neutral-100)
- var(--auro-color-brand-neutral-200)
- var(--auro-color-brand-neutral-300)
- var(--auro-color-brand-neutral-400)
- var(--auro-color-brand-neutral-500)

However, these colors are available in our Figma UI Kit and the tokens are available to engineers, they just are missing from the Auro site.

## Expected behavior
I expect all colors that exist in our UI Kit and that have design tokens to also be available to reference in auro.alaskaair.com

**Comment by blackfalcon** [comment]
I have added the new colors, but I think there are some additional things we need to consider. I am willing to say that the following is out of the scope of this update, but do need to be considered. 

### Digital palette

With these additions, what is the impact on the pre-defined use-case tokens in the [digital palette](https://auro.alaskaair.com/color/core-digital-palette-usage)? Specifically with *border* colors. As I understand the use-case for the new neutral colors is that they are to be used with a new element's borders? 

![Screen Shot 2021-02-09 at 1 19 29 PM](https://user-images.githubusercontent.com/181089/107430007-7d71f580-6ad9-11eb-8201-fa779a2d646f.png)

Also on this same page, we have a section with a listing of `color-base-gray` values. How do these colors compare with the new neutral colors? In the attached screen shot to this issue, there is a listing of `brand-gray`. What are these colors? The released Auro Tokens have no definition for `brand-gray`. 

Is there a record of when this change was made to the design files? Having design files and the released Design Tokens to be out of sync is troubling. 

![Screen Shot 2021-02-09 at 11 28 55 AM](https://user-images.githubusercontent.com/181089/107429480-d0977880-6ad8-11eb-9ae0-90e0e619d594.png)

### New colors

The following is a screen shot of the newly added colors

![Screen Shot 2021-02-09 at 11 29 30 AM](https://user-images.githubusercontent.com/181089/107429818-3e43a480-6ad9-11eb-93a5-8ec77a4bfe72.png)


### Legacy colors

In the listing of all the [design tokens](https://auro.alaskaair.com/getting-started/developers/design-tokens) there are references to pre-existing colors. I am assuming that these will be deprecated? 

![Screen Shot 2021-02-09 at 11 30 44 AM](https://user-images.githubusercontent.com/181089/107429687-09cfe880-6ad9-11eb-871f-89a14ddf5e16.png)

All changes can be seen https://auro-tokens-36.surge.sh/

**Comment by erikalanghauser** [comment]
Hi @blackfalcon  - 
The newly added neutral colors look good to go.

After speaking with UI designers, we should rename the -base-gray-x00s to be **-brand-gray-x00**s and have them fall under the Personality Palette instead of Core Digital Palette.

**-brand-neutral x00**s should also be in the Personality Palette and usage does not need to be specific. Both -brand-gray-x00 and -brand-neutral-x00 are meant to be used as interface accents and are not dedicated solely to borders and the like.

I agree with deprecating the -base-neutrals as they are now replaced by the -brand-neutrals.

One final update would be that:
-base-gray-100 (-brand-gray-100) should be updated to #f7f7f7.

If you need me to move any of this into a new ticket, lmk.

**Comment by blackfalcon** [comment]
@erikalanghauser please see the following updates

The colors `gray` have been removed from the Digital Palette section
https://auro-tokens-36.surge.sh/color/digital-palette

`neutral` and `gray` have been added to the Personality Palette
https://auro-tokens-36.surge.sh/color/personality-palette

`base-gray` was renamed to `brand-gray`
https://auro-tokens-36.surge.sh/color/personality-palette

`base-neutral` colors have been deprecated
https://auro-tokens-36.surge.sh/getting-started/developers/design-tokens/deprecated

`base-gray` colors have been deprecated
https://auro-tokens-36.surge.sh/getting-started/developers/design-tokens/deprecated

**Comment by erikalanghauser** [comment]
@blackfalcon All of the updates look great, thank you!
