### ISSUE TITLE
Add elevation or shadow token support

### ISSUE THREAD

**Issue by littleninja** [AlaskaAirlines/AuroDesignTokens#38]
**Is your feature request related to a problem? Please describe.**
I'm building a fixed button and went to reach for an [elevation token](https://material.angular.io/guide/elevation) or [shadow token](https://tailwindcss.com/docs/box-shadow) but came up empty. I did find `src/shadow.json` marked 'legacy'. Defining consistent elevation planes, which elements exist at each plane (ex. button, card, header), and interactions that lift or lower elevation feel like it has a place in the Auro design system.

**Describe the solution you'd like**
- `auro-shadow-none`
- `auro-shadow-inset`
- `auro-shadow-sm`
- `auro-shadow-md`
- `auro-shadow-lg`

**Describe alternatives you've considered**
n/a. Currently each component [rolls](https://github.com/AlaskaAirlines/auro-button/blob/9edf2ee23ad4678671db9f395c47d85190969043/src/style.scss) [its](https://github.com/AlaskaAirlines/auro-radio/blob/820a647433bbac9591e2116bde931e9f222d1c31/src/auro-radio.scss) [own](https://github.com/AlaskaAirlines/auro-popover/blob/81d095fa78197815b8b3d89855ba0c23c8ecb968/src/style.scss) [shadow](https://github.com/AlaskaAirlines/auro-dialog/blob/d0eaee489248c929c5d8622e73337302c5d27816/src/style.scss), which seems like a design system gap and risk to consistency.

**Additional context**
n/a. Thanks for considering, let me know if you'd like a pull request to draft a first attempt.

**Comment by blackfalcon** [comment]
You are correct. Auro does not have a standard definition for shadows. All the examples you illustrated are unique flowers one way or another. 

What you are building, what is the design spec for that? At the very least we can start there. 

Otherwise, I feel that this is a greater conversation to be had with the UI designers for an official answer.

**Comment by littleninja** [comment]
> What you are building, what is the design spec for that?

A [back-to-top element](https://github.com/littleninja/auro-backtotop), Amanda and Vidal are still working through both UX and UI ([demo here](http://wealthy-feather.surge.sh/)). The fixed position trigger needs a bit of elevation (shadow) and it felt like that's something I would find in design tokens. Similar to how we use consistent colors so they compliment and agree used together on the page, I think there's a case for defining shadows so elements on the page look like they have distinctly same or different elevation.

**Comment by blackfalcon** [comment]
@littleninja I see that the back-to-top element you are creating has a shadow. Is this to be considered for tokenization?

**Comment by littleninja** [comment]
No, the shadow used for back-to-top element is "another unique flower". It's pulled from Angular Material's FAB button: https://material.angular.io/components/button/overview. When we've defined elevation in Auro design system and have shadow tokens to consume, will happily refactor back-to-top.

**Comment by blackfalcon** [comment]
I am punting on this for now. The issue that @littleninja brought up was addressed in the project with yet another custom setting. There is currently no bandwidth for design to address this missing part at this time.

**Comment by blackfalcon** [comment]
Sent an email to the design team for assistance with completing this work.

**Comment by sryckman** [comment]
I've opened a documentation framework for this issue and dropped links to various Figma files where I also see one-off shadows appearing. The doc is otherwise blank and ready for any UI designer to start iterating.

**Comment by blackfalcon** [comment]
@sryckman can you put a link to that Figam file in here? Has there been any movement on this work?

**Comment by blackfalcon** [comment]
This issue has been open for a long time. @leeejune can you see if anyone of the designers want to pick this up?

**Comment by leeejune** [comment]
Explorations here: https://www.figma.com/file/BwHtOWIYLTiBIF2VVy6K9g/Auro-Elevation-%26-Shadows?node-id=407%3A8

**Comment by blackfalcon** [comment]
@leeejune I'd strongly recommend you review this document for your explorations. https://material.io/design/environment/elevation.html#depicting-elevation

**Comment by leeejune** [comment]
Elevation guidelines completed.

**Comment by leeejune** [comment]
@blackfalcon Please review!

**Comment by blackfalcon** [comment]
@leeejune this is GREAT work. The visuals and the content are well done. My only feedback is that for things that have multiple versions of a comment thing, we use the denotation of `100`, `200`, etc... The use of `sm`, `md`, `lg`, really apply to things where specific sizes are used. 

For the naming of these attributes, I would argue that `elevation-100`, `elevation-200` and `elevation-300` would be more consistent. This also allows us a lot more room to grow if there were to be additional elevations added, whereas s, m, l has instant limitations. 

As for development criteria, I would like to see the following explored. 

1. The baseline values for these layers should be added to the auro design token library. 
2. We could add these to the WCSS as a new set of utility classes, e.g. `util__elevation-100`
3. I would like to explore the idea of having an HTML custom element called `auro-elevation` that could act as a declarative wrapper around any content that has a drop shadow. The API would have a prop of `elevation` that accepts a number of `100`, 200`, 300`.

**Comment by leeejune** [comment]
I like the number system over the sizing system. Made those changes just now. I will be presenting this at design fair today.

@blackfalcon What are the next steps? Can this issue be closed?

**Comment by blackfalcon** [comment]
As for development criteria, I would like to see the following explored. 

1. The baseline values for these layers should be added to the auro design token library. 
2. We could add these to the WCSS as a new set of utility classes, e.g. `util__elevation-100`
3. I would like to explore the idea of having an HTML custom element called `auro-elevation` that could act as a declarative wrapper around any content that has a drop shadow. The API would have a prop of `elevation` that accepts a number of `100`, 200`, 300`.
