### ISSUE TITLE
z-index updates

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#40]
**Is your feature request related to a problem? Please describe.**

Z-index use is inconsistently used across AS properties. There are current design tokens, but there needs to be a better definition of the component hierarchy. Currently, popovers are appearing over dialogs, which should be reversed.

**Comment by BrentLabasan** [comment]
Comment so I can be tagged.

**Comment by blackfalcon** [comment]
@BrentLabasan has there been any movement on this issue with the work you are doing?

**Comment by BrentLabasan** [comment]
> @BrentLabasan has there been any movement on this issue with the work you are doing?

PR #43 has been submitted.
