### ISSUE TITLE
Experiment Style Dictionary 3.0

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#41]
# General Support Request

See [scope of changes](https://amzn.github.io/style-dictionary/#/version_3) for Style Disctionay 3.0. 

1. Upgrading to this new version should be backward compatible 
2. Read over the scope of changes and see if there are interesting opportunities to improve the current workflow

**Comment by jason-capsule42** [comment]
Based on review of the new feature set and discussion with @blackfalcon upgrading to Style Dictionary 3.0 is deferred at this time.

The new features are not of immediate value and the version is not officially released yet.
