### ISSUE TITLE
Package includes insecure (possibly unneeded) dependencies

### ISSUE THREAD

**Issue by CarsonTolleshaug** [AlaskaAirlines/AuroDesignTokens#46]
**Describe the bug**
The @alaskaairux/design-tokens package includes a dependency reference to node-gyp package which contains test and debug code. This means that if a project references @alaskaairux/design-tokens and is built into a docker image, that image will get flagged by Aqua scanning (or any other image scanner) and prevented from being promoted.

**To Reproduce**
1. Create project that includes @alaskaairux/design-tokens in packages.json
2. Create dockerfile that installs dependencies and builds the project
3. Build image using dockerfile
4. Scan image with Aqua Scanner

**Expected behavior**
Scan completes with no vulnerabilities

**Screenshots**
See [This Failed Build](https://dev.azure.com/itsals/E_Retain_Account/_build/results?buildId=1726238&view=aquasec.aquasec.build-info-tab)

![aqua-1](https://user-images.githubusercontent.com/11671889/117511741-1ed6df00-af43-11eb-997f-f577f176e36e.png)

Notice it says "remove sensitive data". Here's the sensitive data tab:

![aqua-2](https://user-images.githubusercontent.com/11671889/117511735-1e3e4880-af43-11eb-88a8-173dcfc38be6.png)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser:  N/A
 - Version: 3.1.0

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: 3.1.0

**Additional context**
node-gyp is reference through the @semantic-release/npm plugin. I'm not natively a front-end dev, so my understanding of the process is a bit lacking, but I believe this is used to create an npm package, however I think there is some misconfiguration that has led to it being included in the package itself as well. Hopefully this is enough information to work with.

Cheers!

**Comment by blackfalcon** [comment]
I am not sure what I can do on my end? The [semantic release npm API](https://www.npmjs.com/package/@semantic-release/npm) needs `NPM_TOKEN`. 

This is [NOT set in the code](https://github.com/AlaskaAirlines/AuroDesignTokens/blob/master/package.json#L48-L73) at all. There is a secret in Github that I am using to satisfy this dependency. 

I haven't worked with k8s so I am unsure how to troubleshoot. 

Calling in @tsalright @janabimustafa @gusnaughton @geoffrich

**Comment by gusnaughton** [comment]
@n3rd253 FYI. 

When we ran into this in our project, we ended up having to remove that file manually via the Dockerfile to satisfy the scanner. The argument to be made here is - why are we sending test data in our production containers?

Is there a way we can strip out sub-dependency test information from our production bundles if it's not doing so already?

**Comment by blackfalcon** [comment]
But that's the weird part, it's not? It's a dev dependency. 

https://github.com/AlaskaAirlines/AuroDesignTokens/blob/master/package.json#L21

**Comment by afraalaska** [comment]
As the key seems unrelated to Alaska and has been originated from node-gyp, we can mark this as a false positive on Aqua. 
It would still make sense to exclude non-production code if possible from prod environment.

Seems like this issue's been known by node-gyp, and their reasoning is that they "ship full test and doc functionality with packages and without the key it's not complete."  https://github.com/nodejs/node-gyp/issues/2037

**Comment by blackfalcon** [comment]
> Maybe get better security scanning since this is a pretty odd false positive?

Well, not reaching out to those guys for help. Thanks for finding this @afraalaska. So, what I am getting from this, this is a `won't fix` scenario? So I can close this out? 

@CarsonTolleshaug `devDependencies` by default shouldn't get pulled into prod builds. For example, in a [bundled version](https://www.runpkg.com/?@alaskaairux/auro-button@6.2.0/dist/auro-button__bundled.js) of one of our web components, there are no references to anything that is a devDependency.
