### ISSUE TITLE
Design Tokens: Border colors updates

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/AuroDesignTokens#49]
**Describe the bug**
There is a discrepancy between Figma Border design tokens and the auro.alaskaair.com Border design tokens.
var(--auro-color-border-primary-on-light) & var(--auro-color-border-primary-on-dark) need updated to new hex values. 
and 2 border-**divider** colors need added.

**To Reproduce**
1. View the breakdown of Figma border colors vs Auro border colors in this Figma file https://www.figma.com/file/ufoYH9MYNkD26P7ywVQ0fP/Debugging?node-id=15%3A1465

**Expected behavior**
Update 2 existing tokens:
var(--auro-color-border-primary-on-light) to #626B79
var(--auro-color-border-primary-on-dark) to #9FABBB

Add 2 new tokens:
var(--auro-color-border-divider-on-light) to rgba(0, 0, 0, 0.15)
var(--auro-color-border-divider-on-dark) to #FFFFFF

**Screenshots**
![image](https://user-images.githubusercontent.com/34354487/119571610-66909f80-bd66-11eb-991b-b57f439ba9b9.png)

**Desktop (please complete the following information):**
 - OS mac
 - Browser chrome

## Exit criteria 

Tokens are updated and new tokens added. 

auro-input https://github.com/AlaskaAirlines/auro-input/issues/37

**Comment by erikalanghauser** [comment]
Additional context: 
auro-input line color currently appears incorrect but is using the correct -primary-on-light token. Updating the tokens will give it the proper #626B79 line color. 
The current primary-on-light color is too light and very much resembles the -disabled-on-light token which is undesirable. This color is better leveraged as a -border-divider only.

@audreychae97 @bridgetglewis

**Comment by blackfalcon** [comment]
@erikalanghauser yes, auro-input is pretty behind in regards to tokens. Once we have this update published, I will get auro-input up to date.
