### ISSUE TITLE
Auro design tokens: Oneworld/MP Tier tokens

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/AuroDesignTokens#56]
We have an upcoming 100k tier being added to the Mileage Plan program.

Sometimes I see these tiers with different colors.  Should we add design tokens for these tiers so its easier to implement and is consistent?

@vidalmenAS I'd love to discuss this one with you.

Million miler uses #767676
https://www.alaskaair.com/content/mileage-plan/membership-benefits?lid=mileageplan:mileage-plan-overview:membership-benefits

One world does use colors to denote each tier that we should create tokens for.

https://cdn4.loyaltylobby.com/wp-content/uploads/2014/12/Oneworld-Enhanced-Sapphire-Benefits-Table.png

**Comment by leeejune** [comment]
Added oneworld and AA tier colors: https://www.figma.com/file/TBMhIMVRMkufKnyxqGzrZO/Color-Explorations?node-id=33%3A2629

Waiting for review.

**Comment by blackfalcon** [comment]
@leeejune Suggestion:  `Token name: auro-color-oneworld-tier-ruby` 

Tier is a child concept of OneWorld.

**Comment by leeejune** [comment]
@blackfalcon Should that apply to `auro-color-tier-alaska-mvp-on-light` as well?

**Comment by braven112** [comment]
> @braven112 The oneworld link doesn't work for me. Is there another link I can access?

I think it was the blue, green and red from this page:
https://www.oneworld.com/travel-benefits

![image](https://user-images.githubusercontent.com/5118118/146455666-5ffe7082-e561-435a-9534-4d876a9f5481.png)

I would reach out the the designer on the loyalty team to double check the exact hex value.

**Comment by blackfalcon** [comment]
@leeejune here is what we need to do. 

We need to create the baseline token that is these colors. Like we have `var(--auro-color-brand-goldcoast-200)`

Then those baseline tokens will be aliased to `auro-color-oneworld-tier-ruby` and `auro-color-alaska-tier-mvp`

Are there `onDark` versions of these colors? The OneWorld site doesn't appear to support a dark mode, so my guess is no.

**Comment by leeejune** [comment]
> Are there `onDark` versions of these colors? The OneWorld site doesn't appear to support a dark mode, so my guess is no.

There is no onDark for OneWorld. Alaska has onDark for MVP Gold and MVP.

**Comment by leeejune** [comment]
https://www.figma.com/file/TBMhIMVRMkufKnyxqGzrZO/Color-Explorations?node-id=107%3A1869


Updated with baseline color names and alias color tokens. Please review @blackfalcon!

**Comment by leeejune** [comment]
I will be adding the tokens to the code with Dale's help.
