### ISSUE TITLE
Add XXS font size

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/AuroDesignTokens#70]
## Is your feature request related to a problem? Please describe.
Designers need smaller font sizes for labels or less significant information.

## Describe the solution you'd like
Add a smaller font size (XXS).

```
font-family: 'AS Circular';
font-style: normal;
font-weight: 400;
font-size: 10px;
line-height: 14px;
/* identical to box height, or 140% */

font-feature-settings: 'liga' off;

```

## Exit criteria 
A new font-size token will be created and added to the list of supported sizes. 

An update to the docs site type page provides clear guidelines that warn users of using this XXS font for disclaimers/legal content. We also need to speak to why this is different from our current `fineprint` support.

**Comment by blackfalcon** [comment]
@leeejune and I talked about this, it's a 👍 from me to do this work.
