### ISSUE TITLE
Refactor size spacing values

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/AuroDesignTokens#71]
**Is your feature request related to a problem? Please describe.**
Content uses 90px spacing between large content sections. There is no token that fits this need.

**Describe the solution you'd like**
Add a 90px spacing after our XXXL 64px spacing token.

**Describe alternatives you've considered**
One suggestion made was to add two spacing tokens together (64px + 24px), but it is not an efficient way to integrate larger spacing.

**Additional context**
Naming might need to be reconsidered as the number of X's could feel overwhelming.
Content uses 90px in most of their pages.

**Next steps**

- [ ] Add to Figma library

**Comment by blackfalcon** [comment]
I feel like having a 90px option is a result of how our grid solution [didn't really think to accommodate this](https://auro.alaskaair.com/layout/grid#:~:text=Fixed-,Guidlines,-Two%20grid%20sizes).

I look at how Material had [alternate grid solutions per different media types](https://material.io/design/layout/responsive-layout-grid.html#columns-gutters-and-margins).  We simply cram 12 columns into a smaller space. 

Looking at [Spectrum](https://spectrum.adobe.com/page/responsive-grid/) they take a very comprehensive approach to their layout and the concept of regions. E.g. if you have a layout that is three regions of 4 columns each, is the full layout 3 columns or 12? 

The more we embrace these kinds of concepts the simpler we can make an official grid/layout system.

**Comment by leeejune** [comment]
The 90px spacing would be used for vertical spacing and the grid system only accommodates horizontal spacing. The content team separates large groups of content with 90px of space.

However, I like the solution of having different grids for screen sizes. Seems like it belongs more in this issue: https://github.com/AlaskaAirlines/WebCoreStyleSheets/issues/114

**Comment by braven112** [comment]
Let's sync up with Amanda's template work and come up with a list of all potential tokens

**Comment by blackfalcon** [comment]
What is the status of this @leeejune? Has this been addressed outside the scope of tokens or is there still a need to solve this problem?

**Comment by leeejune** [comment]
@blackfalcon Content still seems to be needing a larger spacing token. We were thinking 80px (5rem) could work.

**Comment by blackfalcon** [comment]
@leeejune I am thinking that we painted ourselves into a corner with our current naming strategy. Looking at other design systems, where we embraced a naming convention like -100 and -200 in some parts, why we did not do this universally I don't know, but maybe we can now. 

See https://spectrum.adobe.com/page/design-tokens/#Size-tokens

Let's talk about how we can look at going in an alternate direction and look to deprecate the existing `xxl` convention.

**Comment by leeejune** [comment]
Proposed token naming: https://alaskaair-my.sharepoint.com/:x:/p/june_lee/EYsMP9O8OY1Og8W1rG-YUcUBoc0RsrDFeDoe3FMz2btuoQ?e=30ezgE

**Comment by braven112** [comment]
Naming is hard.  Here are how 4 other design system do it.  I personally find the proposed number system confusing especially if we only support some of the values in the 100, 200 format.

https://carbondesignsystem.com/guidelines/spacing/overview/#spacing
https://www.lightningdesignsystem.com/design-tokens/#category-spacing
https://design.gs.com/foundation/spacing
https://momentum.design/tokens/space

I think one of 2 options would work:

1. Option 1 embrace the t-shirt size way but simplify to 4XL vs XXXXL.   I think this one is the most intuitive to use.  Downside is that from a practical stand point it makes it king of hard to do a 3.5XL if we wanted something in between in the future. 
2. Option 2 use the 100 system but simplify the ramp up like so...

![Image](https://user-images.githubusercontent.com/5118118/185466858-4d90f82a-0283-45cb-a5e7-029a2c91ecf2.png)

Then we still have the option of doing 950 or 850 if the need presents itself.

**Comment by jason-capsule42** [comment]
I like the 100->200->300,... naming convention. It's easier to read and I agree it leaves room for extending to other increments more easily.

That said, I hope we don't go and create too many of these. It seems half of the point of them is to create consistent usage of layout dimensions. The more we create the more we have variation in the design. Not my area I know... but there has to be a line in the sand somewhere about how many of these we are going to support.

**Comment by blackfalcon** [comment]
@leeejune there are solid use cases for t-shirt vs 100 scale, and I agree we can stick wth the t-shirts for type. Given the examples @braven112 used, this appears to be a real sticky issue with many systems. 

IMHO, t-shirts and spacing just didn't work because of the many nuances designers are looking for. Vs type where there are few if no in-between things happening. 

I'd love to know how many custom sized are being used in production? What's interesting is that we have a scale of 4+ then it jumps to 8+ 

Something else I noticed. This scale is all based on 8s. Ok, so let's really own that concept here. This scale at least allows for something between 2x and 3x whereas the current system won't support 56px. 

Current | px | rem | New name | 
|---|---|---|---|
|4xl|80px|5rem|1000|
|3xl|64px|4rem|800|
|2xl|48px|3rem|600|
|xl|32px|2rem|400|
|l|24px|1.5rem|300|
|m|16px|1rem|200|
|s|12px|0.75rem|150|
|xs|8px|0.5rem|100|
|2xs|4px|0.25rem|50|
|3xs|2px|0.125rem|25|
|4xs|0|0|0|

**Comment by leeejune** [comment]
@blackfalcon What you have in that table is actually exactly what I have! Seems like we are on the same page.

![Screen Shot 2022-08-23 at 9 56 06 AM](https://user-images.githubusercontent.com/55998746/186218068-eb9d7f5a-a6f0-417f-85db-dbf7d5ad100b.png)

**Comment by blackfalcon** [comment]
@leeejune close, but ... check out 3XL. It should be 800, not 900.

**Comment by leeejune** [comment]
@blackfalcon Oop, faulty human calculation 😆 Will make the edit. Are we going with this solution?

**Comment by blackfalcon** [comment]
Acceptance criteria:

1. New tokens are added
2. Legacy tokens are marked as `deprecated`
3. DO NOT DELETE legacy token names
4. DO NOT add new token with legacy name convention
5. Code commit is `feat:`

|Current token | Newly added token | Value |
|---|---|---
| n/a | var(--auro-size-1000) | 5rem
|var(--auro-size-xxxl) | var(--auro-size-800) | 4rem
|var(--auro-size-xxl) | var(--auro-size-600) | 3rem
|var(--auro-size-xl) | var(--auro-size-400) | 2rem
|var(--auro-size-lg) | var(--auro-size-300) | 1.5rem
|var(--auro-size-md) | var(--auro-size-200) | 1rem
|var(--auro-size-sm) | var(--auro-size-150) | 0.75rem
|var(--auro-size-xs) | var(--auro-size-100) | 0.5rem
|var(--auro-size-xxs) | var(--auro-size-50) | 0.25rem
|var(--auro-size-xxxs) | var(--auro-size-25) | 0.125rem
|var(--auro-size-none) | var(--auro-size-0) | 0

**Comment by blackfalcon** [comment]
Already seeing an opportunity for `var(--auro-size-500)` e.g. 2.5rem/40px. 

See this PR: https://github.com/AlaskaAirlines/auro-select/pull/98/files

**Comment by blackfalcon** [comment]
New issue to update WCSS to support this update

- https://github.com/AlaskaAirlines/WebCoreStyleSheets/issues/121
