### ISSUE TITLE
v3.12 broke the deprecated tokens output

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#93]
## Describe the bug

Installing 3.12 into the Auro dociste, broke the UI output of the deprecated tokens. 

## To Reproduce

1. Use a local version of the docsite 
1. Update with this command `npm i @alaskaairux/design-tokens@3.12.1`
1. Run the server locally
1. Go to http://localhost:3000/getting-started/developers/design-tokens/deprecated
1. See the error

## Expected behavior

A list of deprecated tokens and related information should be displayed 

## Additional context

This issue will not appear on `master` or in the production docsite as it was rolled back to use `@alaskaairux/design-tokens@3.11.0`

It has been determined that the root of this issue is the change to the design tokens. There were no other charges to the docsite or auro-tokenlist that would have caused this issue. Also, reverting the docsite to v3.11 resolved the issue temporarily. 

## Scope of the issue 

The differences between [@alaskaairux/design-tokens@3.11.0](https://unpkg.com/@alaskaairux/design-tokens@3.11.0/dist/tokens/JSObject--deprecated.js) and [@alaskaairux/design-tokens@3.12.0](https://unpkg.com/@alaskaairux/design-tokens@3.12.1/dist/tokens/JSObject--deprecated.js) need to be reviewed and determined what is causing the issue for the deprecated file output issue. 

## Exit criteria 

This issue will be considered closed once an update is applied that will allow the deprecated tokens page to render correctly based  on an updated `JSObject--deprecated.js` file.

**Comment by blackfalcon** [comment]
Reviewed with the team, and gave it a size `M` due to the complexity of the error. There is a working theory that due to the last updates the tokens actually run twice and in that process, it may be outputting a corrupt deprecated JS object that is not useable by the site. 

This issue will require some time for reviewing the last update and how that interacts with the deprecated object. 

The team feels strongly that the theory is the issue and if that is the case, then the fix is pretty straight forward. 

The engineer who takes on the work, please be sure to report findings prior to executing if there is any additional complexity as to update the size of the work.

**Comment by jordanjones243** [comment]
After doing investigative work, the reason that the deprecated list of tokens will not compile, nor display, is because of an error coming from `auro-tokenlist`; the element that is responsible for building out the list of tokens. In `auro-tokenlist`. All of the `color` tokens are failing on a method called `currentToken` which takes in a parameter referring to the `reference` object within the JSON data, which none of the `color` tokens have.

All of the `color` tokens need to add a `reference` object within their data that either has a value of the "current token" or "n/a".

**Comment by jordanjones243** [comment]
Reference this new issue for the context behind this bug and the continued work: 
- https://github.com/AlaskaAirlines/AuroDesignTokens/issues/96
