### ISSUE TITLE
Deprecate on-light tokens concept

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#98]
# General Support Request

Moving forward with a light mode vs dark mode strategy versus on-dark and on-light, most of the on-dark tokens have been deprecated. This leaves behind a long list of on-light tokens that no longer make sense. 

## Support request

In some cases, there is a need for on-dark versions. Having this option requires a sub-node past the color definition. E.g. we cannot have `var(--auro-color-tier-alaska-mvp)` and `var(--auro-color-tier-alaska-mvp-on-dark)`. 

## Possible Solution

A recommendation is to move to a more neutral name, e.g. `var(--auro-color-tier-alaska-mvp-default)` and rename any needed on-dark versions to `inverse` e.g. `var(--auro-color-tier-alaska-mvp-inverse)`

## Exit criteria 

This issue will be considered complete once the token names have been updated and the legacy tokens have been labeled as deprecated with the proper new reference.

**Comment by blackfalcon** [comment]
Let's make sure that we keep in mind the opportunities outlined in this issue when moving forward

- https://github.com/AlaskaAirlines/AuroDesignTokens/issues/99

**Comment by blackfalcon** [comment]
The following issue is a pre-requisite to this work. 

- https://github.com/AlaskaAirlines/AuroDesignTokens/issues/102

**Comment by blackfalcon** [comment]
Added ADO reference link to test out communication between platforms.

**Comment by blackfalcon** [comment]
Is set as READY TO WORK, but has a dependency on @leeejune completing the Figma reference.

**Comment by leeejune** [comment]
Renaming work is complete here: https://alaskaair-my.sharepoint.com/:x:/p/june_lee/EdaRLHWZS1ZFs4s8kFLJ15MBTYqJ52scti3SHvmK6-XrJg?e=12uuMg

**Comment by leeejune** [comment]
> Is set as READY TO WORK, but has a dependency on @leeejune completing the Figma reference.

What Figma reference are you referring to?
